# Use an R base image from Docker Hub
FROM rocker/tidyverse:latest

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev

# Install R packages
RUN R -e "install.packages('devtools', repos = 'http://cran.rstudio.com/')"
RUN R -e "remotes::install_github('mathesong/bloodstream', FORCE = TRUE)"

# Create the R script
RUN printf "# run_bloodstream.R\nbids_dir <- file.path('/data')\nconfig_file <- file.path(bids_dir, 'code/bloodstream', 'config.json')\n\n# Load necessary libraries\nlibrary(bloodstream)\n\n# Execute bloodstream\nbloodstream(bids_dir, config_file)" > run_bloodstream.R

# Command to run your R script
CMD ["Rscript", "run_bloodstream.R", "/data/code/bloodstream/config.json"]
